Name:           ros-indigo-shadow-robot-ethercat
Version:        1.3.3
Release:        0%{?dist}
Summary:        ROS shadow_robot_ethercat package

Group:          Development/Libraries
License:        GPL
URL:            http://ros.org/wiki/shadow_robot_ethercat
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-sr-edc-controller-configuration
Requires:       ros-indigo-sr-edc-ethercat-drivers
Requires:       ros-indigo-sr-edc-launch
Requires:       ros-indigo-sr-edc-muscle-tools
Requires:       ros-indigo-sr-external-dependencies
Requires:       ros-indigo-sr-robot-lib
BuildRequires:  ros-indigo-catkin

%description
This stack contains the drivers and the controllers for Shadow Robot's EtherCAT
Hand.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.3-0
- Autogenerated by Bloom

