Name:           ros-indigo-sr-edc-ethercat-drivers
Version:        1.3.3
Release:        0%{?dist}
Summary:        ROS sr_edc_ethercat_drivers package

Group:          Development/Libraries
License:        GPL
URL:            http://ros.org/wiki/sr_edc_ethercat_drivers
Source0:        %{name}-%{version}.tar.gz

Requires:       binutils-devel
Requires:       ros-indigo-message-runtime
Requires:       ros-indigo-ros-ethercat-hardware
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-roslib
Requires:       ros-indigo-sr-external-dependencies
Requires:       ros-indigo-sr-robot-lib
Requires:       ros-indigo-sr-robot-msgs
Requires:       ros-indigo-std-msgs
BuildRequires:  binutils-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-ros-ethercat-hardware
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-roslib
BuildRequires:  ros-indigo-sr-external-dependencies
BuildRequires:  ros-indigo-sr-robot-lib
BuildRequires:  ros-indigo-sr-robot-msgs
BuildRequires:  ros-indigo-std-msgs

%description
A package implementing a ROS interface for the etherCAT Shadow Robot Dextrous
Hand.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.3-0
- Autogenerated by Bloom

