Name:           ros-hydro-sr-robot-lib
Version:        1.3.4
Release:        0%{?dist}
Summary:        ROS sr_robot_lib package

Group:          Development/Libraries
License:        GPL
URL:            http://ros.org/wiki/sr_robot_lib
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-diagnostic-updater
Requires:       ros-hydro-pr2-mechanism-msgs
Requires:       ros-hydro-realtime-tools
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-sr-ethercat-hand-config
Requires:       ros-hydro-sr-external-dependencies
Requires:       ros-hydro-sr-hardware-interface
Requires:       ros-hydro-sr-robot-msgs
Requires:       ros-hydro-sr-self-test
Requires:       ros-hydro-sr-utilities
Requires:       ros-hydro-std-srvs
BuildRequires:  gtest-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-diagnostic-updater
BuildRequires:  ros-hydro-pr2-mechanism-msgs
BuildRequires:  ros-hydro-realtime-tools
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rostest
BuildRequires:  ros-hydro-sr-external-dependencies
BuildRequires:  ros-hydro-sr-hardware-interface
BuildRequires:  ros-hydro-sr-robot-msgs
BuildRequires:  ros-hydro-sr-self-test
BuildRequires:  ros-hydro-sr-utilities
BuildRequires:  ros-hydro-std-srvs

%description
sr_robot_lib contains the robot library used in the sr_edc_ethercat_drivers. The
library is used to store the incoming etherCAT messages in an easy to access
format, and prepare the messages to be send through etherCAT.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Fri Sep 19 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.4-0
- Autogenerated by Bloom

